name: dart_discord_rpc
description: Discord Rich Presence for Flutter & Dart apps & games.
version: 0.0.1
repository: https://github.com/alexmercerind/dart_discord_rpc
homepage: https://github.com/alexmercerind/dart_discord_rpc

environment:
  sdk: ">=3.0.0"

dependencies:
  ffi: ^2.0.2
  path: ^1.8.3
  file: ^6.1.4

dev_dependencies:
  ffigen: ^8.0.2

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: DartDiscordRpcPlugin
      windows:
        pluginClass: DartDiscordRpcPlugin

ffigen:
  output: "lib/generated/bindings.dart"
  dart-bool: true
  headers:
    entry-points:
      - "headers/discord_register.h"
      - "headers/discord_rpc.h"
  name: "DiscordRPC"
  description: "Dart bindings to Discord RPC client."
